[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml
srun=mkdir -p $MESH_DIR ; srun --ntasks=1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml

[namelist:cubedsphere_mesh]
edge_cells=24,12,6,3

[namelist:mesh]
mesh_maps='l0_cubedsphere:l1_cubedsphere',
         ='l1_cubedsphere:l2_cubedsphere',
         ='l2_cubedsphere:l3_cubedsphere'
mesh_names='l0_cubedsphere','l1_cubedsphere','l2_cubedsphere',
          ='l3_cubedsphere'
n_meshes=4
partition_mesh=.true.

[namelist:partitions]
generate_inner_halos=.true.
max_stencil_depth=5
n_partitions=6
partition_range=0,5
