[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/planar_mesh_generator mesh_generation.nml
srun=mkdir -p $MESH_DIR ; srun --ntasks=1 $BIN_DIR/planar_mesh_generator mesh_generation.nml

[env]
mesh_generator=Planar

[!!namelist:cubedsphere_mesh]

[namelist:mesh]
mesh_maps='l0_planar:l1_planar','l1_planar:l2_planar',
         ='l2_planar:l3_planar','l0_planar:l3_planar'
mesh_names='l0_planar','l1_planar','l2_planar','l3_planar'
n_meshes=4
rotate_mesh=.true.
topology='non_periodic'

[namelist:planar_mesh]
domain_centre=0.0,-15.0
domain_size=90.0,60.0
edge_cells_x=48,24,12,6
edge_cells_y=48,24,12,6
periodic_x=.false.
periodic_y=.false.

[namelist:rotation]
rotation_target='null_island'
target_null_island=0.0,20.0
