[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml
srun=mkdir -p $MESH_DIR ; srun --ntasks=1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml

[namelist:cubedsphere_mesh]
edge_cells=24,12,6,3
equatorial_latitude=16.26020471

[namelist:mesh]
mesh_maps='l0_cubedsphere:l1_cubedsphere',
         ='l1_cubedsphere:l2_cubedsphere',
         ='l2_cubedsphere:l3_cubedsphere'
mesh_names='l0_cubedsphere','l1_cubedsphere','l2_cubedsphere',
          ='l3_cubedsphere'
n_meshes=4
