[file:lfric2lfric_clim_gal9_C12_MG.nc]
source="$BIG_DATA_DIR/start_dumps/proto-ral/AppsTicket110/lfric_atm_clim_gal9_C12_dt-1800p0_intel_64-bit_fast-debug_000072.nc"

[namelist:lfric2lfric]
source_meshfile_prefix='${MESH_DIR}/C12/mesh_C12'

[namelist:files]
start_dump_filename='lfric2lfric_clim_gal9_C12_MG'