[namelist:files]
checkpoint_stem_name='restart_lfric2lfric_ral_seuk_MG'

[namelist:lfric2lfric]
target_domain='LAM'
dst_ancil_directory='$BIG_DATA_DIR/ancils/proto-ral/Ticket3510/seuk'
destination_meshfile_prefix='${MESH_DIR}/seuk_MG/mesh_seuk_MG'
destination_mesh_name='l0_planar'
dst_orography_mean_ancil_path='orography/gmted_ramp2/qrparm.orog.ugrid'
destination_topology='non_periodic'

[namelist:partitioning(destination)]
partitioner='planar'
