[namelist:lfric2lfric]
destination_mesh_name='l0_cubedsphere'
destination_meshfile_prefix='${MESH_DIR}/C24_C12/mesh_C24_C12'
source_mesh_name='l1_cubedsphere'
source_meshfile_prefix='${MESH_DIR}/C24_C12/mesh_C24_C12'
