[namelist:files]
checkpoint_stem_name='restart_lfric2lfric_ral_ukv_MG'

[namelist:lfric2lfric]
target_domain='LAM'
dst_ancil_directory=''
destination_meshfile_prefix='${MESH_DIR}/ukv_MG/mesh_ukv_MG'
destination_mesh_name='l0_planar'
dst_orography_mean_ancil_path=''
destination_topology='non_periodic'

[namelist:partitioning(destination)]
partitioner='planar'
