[file:mesh_C48.nc]
mode=auto
source=$MESH_DIR/mesh_C48.nc

[namelist:base_mesh]
!!f_lat_deg=
file_prefix='mesh_C48'
!!fplane=
geometry='spherical'
prime_mesh_name='l0_cubedsphere'

[namelist:partitioning]
partitioner='cubedsphere'
