[file:mesh_C24_MG.nc]
mode=auto
source=$MESH_DIR/mesh_C24_MG.nc

[namelist:base_mesh]
!!f_lat_deg=
file_prefix='mesh_C24_MG'
!!fplane=
geometry='spherical'
prime_mesh_name='l0_cubedsphere'

[namelist:multigrid]
chain_mesh_tags='l0_cubedsphere','l1_cubedsphere','l2_cubedsphere',
               ='l3_cubedsphere'
multigrid_chain_nitems=4

[namelist:partitioning]
partitioner='cubedsphere'
